### PR TITLE
Fix case where large BAM header causes "no reads in first split" error.

### PR DESCRIPTION
**Pull request by tomwhite**
This should fix https://github.com/bigdatagenomics/adam/issues/896. I tried the fix on a BAM file supplied by @heuermh and the exception no longer occurs.

### CODE REVIEW

**Comment by heuermh** [comment]
Works for me in ADAM.  Thank you, @tomwhite!

**Comment by tomwhite** [comment]
Thanks for trying it out @heuermh. I'd like to commit this soon unless there are any objections.

**Comment by AndreSchumacher** [comment]
That's an interesting bug. Maybe BAM headers have grown in size of the years? :-) Thanks @tomwhite for the fix. This looks good to me.

**Comment by tomwhite** [comment]
Thanks for the review @AndreSchumacher.

**Pull request merged**
