### PR TITLE
Fix VCFHeaderReader for gzipped and BGZF VCF formats

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #96

### CODE REVIEW

**Comment by tomwhite** [comment]
@heuermh, does this look OK to you? I'd like to merge this soon.

**Comment by heuermh** [comment]
+1

Yes, works for me.  Thank you, @tomwhite

**Comment by tomwhite** [comment]
Thanks for checking @heuermh.

**Comment by fnothaft** [comment]
Thanks for the fix, @tomwhite!

**Pull request closed without merging**
