### PR TITLE
bump htsjdk dependency version to 2.20.3

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Review by tomwhite — APPROVED** [review]
Looks good. Please rebase and rerun tests.

**Comment by tomwhite** [comment]
Thanks @heuermh!

**Comment by heuermh** [comment]
@tomwhite Could you deploy an 8.0.0-SNAPSHOT?  I don't have write access to the `org.seqdoop` groupId on Sonatype Nexus.

**Comment by tomwhite** [comment]
@heuermh I just tried to deploy the snapshot but a got a 401. Not sure why, but I haven't tried for a while. I'll see if I can find out what's happening.

**Comment by tomwhite** [comment]
Actually, Travis automatically deploys snapshots, so you should find that it's published already.

**Pull request merged**
