### PR TITLE
Add an option to ensure paired reads are in the same split.

### PR DESCRIPTION
**Pull request by tomwhite**
Here's my first attempt at this (#43). Probably needs more testing beyond the unit tests I've written.

### CODE REVIEW

**Comment by droazen** [comment]
Would someone more familiar with this codebase than us (the GATK team) be available to take a look at this change and let us know if it's sane? Our goal is to be able to safely accept queryname-sorted input in our Spark tools without having to do a `groupByKey` on the read name and without having to worry about read pairs getting assigned to different partitions. Thanks!

**Comment by droazen** [comment]
@laserson, perhaps?

**Comment by laserson** [comment]
I'm not really familiar with this codebase.  I'll tag @fnothaft or @ryan-williams

**Comment by droazen** [comment]
@AndreSchumacher would you be able to take a look at this one when you have time?

**Comment by AndreSchumacher** [comment]
From my understanding the logic makes sense (assuming that queryname sort order does indeed place both reads of a pair consecutively in the right order which seems to be the case).

The case I was wondering about: let's say in some QC step you filter out reads disregarding of whether they are paired or not and later on you want to read the output of that back in, using this option. If there is a second read of a pair at the beginning of some split whose mate was filtered out then this read will be silently dropped. Is it enough to have a warning in the docs that if one uses this option one needs to ensure that all read pairs are properly paired?

**Comment by tomwhite** [comment]
Thanks for taking a look @AndreSchumacher. I think your analysis is right, although I don't know how often that would come up in practice. Perhaps @droazen could comment? I've added some documentation to the property to warn about this possibility.

**Comment by tomwhite** [comment]
I've updated the code to simplify the logic a little, so that #34 is easier to integrate. The idea is to change `BamRecordReader#nextKeyValue` so that it is a while loop rather than a single if statement, since a while loop allows reads to be filtered out (if they are not the first in a pair for this issue, or if they aren't in an interval for #34).

**Comment by AndreSchumacher** [comment]
Thanks @tomwhite for simplifying the logic, I think it's now much more clear. One final comment: I don't think it could cause problems but I would feel better also initializing <code>readPair</code> and <code>lastOfPair</code> in the <code>initialize()</code> function.

**Comment by tomwhite** [comment]
Thanks for the review @AndreSchumacher. I've added the initialization you suggested, squashed the commits, and will now merge.

**Pull request merged**
