### PR TITLE
Extend AnySAMInputFormat to support CRAM.

### LINKED ISSUE #35: Extend AnySAMInputFormat to support CRAM
Currently it supports SAM and BAM files, but with the addition of CRAMInputFormat it should support CRAM files too.

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #35.

### CODE REVIEW

**Comment by tomwhite** [comment]
@AndreSchumacher does this look OK to you?

**Comment by AndreSchumacher** [comment]
Thanks @tomwhite for the PR. I will look at this later today in the evening.

**Comment by tomwhite** [comment]
Thanks Andre.

**Comment by AndreSchumacher** [comment]
Looking good to me, I would say that is ready to get merged. Good idea actually to add CRAM to the AnySAM group of input formats.

**Pull request merged**
